version: "2"

linters-settings:
  errcheck:
    exclude-functions:
      - os.Setenv
      - os.Unsetenv
      - fmt.Fprint
      - fmt.Fprintf
      - fmt.Fprintln

issues:
  exclude-rules:
    - linters:
        - errcheck
      source: "Close\\(\\)"
